[project]
name = "clarity-nft"
requirements = []

[contracts.sip009-nft-trait]
path = "contracts/sip009-nft-trait.clar"
depends_on = []

[contracts.pogs]
path = "contracts/pogs.clar"
depends_on = ["sip009-nft-trait"]
